name: "Deploy ERP AWS - Prod"

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  prod:
    uses: PixelTech-Solutions/Terraform/.github/workflows/terraform.yml@main
    with:
      working_directory: ./infra/aws
      environment: prod
      project_name: erp-system
      service_name: aws
    secrets: inherit
